name: Release & Publish
on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install the dependencies
      run: npm install

    - name: Configure Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
  
    - name: Create and publish release
      id: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm run release

    - name: Get Latest Tag
      id: get_tag
      run: echo "release_version=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

    - name: Send Teams Notification
      if: steps.release.outcome == 'success'
      run: |
        curl -H 'Content-Type: application/json' \
            -d '{
              "@type": "MessageCard",
              "summary": "New Release Available",
              "themeColor": "0076D7",
              "title": "🚀 New Release Published!",
              "text": "A new release has been published for the **${{ github.repository }}** repository:\n\n**Version**: ${{ env.release_version }}\n\nPlease check the [release notes](https://github.com/${{ github.repository }}/releases/tag/${{ env.release_version }}) for detailed information on the changes and improvements. \n\n**Important**: Ensure that you update this dependency in your projects that use it. Pay special attention to any breaking changes and adapt your code accordingly.\n\nThank you!",
              "sections": [
                {
                  "facts": [
                    {
                      "name": "Repository",
                      "value": "${{ github.repository }}"
                    },
                    {
                      "name": "Version",
                      "value": "${{ env.release_version }}"
                    }
                  ]
                }
              ],
              "potentialAction": [
                {
                  "@type": "OpenUri",
                  "name": "View Release",
                  "targets": [
                    {
                      "os": "default",
                      "uri": "https://github.com/${{ github.repository }}/releases/tag/${{ env.release_version }}"
                    }
                  ]
                }
              ]
            }' \
            ${{ secrets.TEAMS_WEBHOOK }}
    