name: CI/CD
on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
jobs:
  pipeline:
    uses: poc-gh-actions/workflow/.github/workflows/main.yaml@main
    secrets: inherit