name: CI/CD
on: 
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
jobs:
  pipeline:
    uses: poc-gh-actions/release-it/.github/workflows/flow/flow.yml@main
    secrets: inherit